//
// CBFullNetworkLicense.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBFullNetworkLicense {

    public var name: String?
    public var url: String?

    public init(name: String?, url: String?) {
        if let name = name {
            self.name = name
        }
        if let url = url {
            self.url = url
        }
    }

    init(json: JSON) throws {
        let name = json["name"].string
        let url = json["url"].string
        self.name = name
        self.url = url
    }
}

extension CBFullNetworkLicense {

    func toParams() -> APIParams {
        var params = [String: Any]()
        if let name = name { params["name"] = name }
        if let url = url { params["url"] = url }
        return params
    }

}

