//
// CBFullNetwork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBFullNetwork {

    public var id: String?
    public var name: String?
    public var href: String?
    public var company: [String]?
    public var license: CBFullNetworkLicense?
    public var location: CBShortNetworkLocation?
    public var stations: [CBStation]?

    public init(id: String?, name: String?, href: String?, company: [String]?, license: CBFullNetworkLicense?, location: CBShortNetworkLocation?, stations: [CBStation]?) {
        if let id = id {
            self.id = id
        }
        if let name = name {
            self.name = name
        }
        if let href = href {
            self.href = href
        }
        if let company = company {
            self.company = company
        }
        if let license = license {
            self.license = license
        }
        if let location = location {
            self.location = location
        }
        if let stations = stations {
            self.stations = stations
        }
    }

    init(json: JSON) throws {
        let id = json["id"].string
        let name = json["name"].string
        let href = json["href"].string
        var company = [String]()
        if let companyJSON = json["company"].array {
            for json in companyJSON {
                if let object = json.string {
                    company.append(object)
                }
            }
        }
        let license = try? CBFullNetworkLicense(json: json["license"])
        let location = try? CBShortNetworkLocation(json: json["location"])
        var stations = [CBStation]()
        if let stationsJSON = json["stations"].array {
            for json in stationsJSON {
                do {
                    let object = try CBStation(json: json)
                    stations.append(object)
                } catch let error {
                    print(error)
                }
            }
        }
        self.id = id
        self.name = name
        self.href = href
        self.company = company
        self.license = license
        self.location = location
        self.stations = stations
    }
}

extension CBFullNetwork {

    func toParams() -> APIParams {
        var params = [String: Any]()
        if let id = id { params["id"] = id }
        if let name = name { params["name"] = name }
        if let href = href { params["href"] = href }
        params["company"] = self.company
        if let license = license { params["license"] = license }
        if let location = location { params["location"] = location }
        if let objects = self.stations {
            var stations = [[String: Any]]()
            for object in objects {
                if let param = object.toParams() {
                    stations.append(param)
                }
            }
            params["stations"] = stations
        }
        return params
    }

}

