//
// CBNetworkDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBNetworkDetails {

    public var network: CBFullNetwork

    public init(network: CBFullNetwork) {
        self.network = network
    }

    init(json: JSON) throws {
        let network = try CBFullNetwork(json: json["network"])
        self.network = network
    }
}

extension CBNetworkDetails {

    func toParams() -> APIParams {
        var params = [String: Any]()
        params["network"] = network
        return params
    }

}

