//
// CBNetworksList.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBNetworksList {

    public var networks: [CBShortNetwork]

    public init(networks: [CBShortNetwork]) {
        self.networks = networks
    }

    init(json: JSON) throws {
        var networks = [CBShortNetwork]()
        if let networksJSON = json["networks"].array {
            for json in networksJSON {
                do {
                    let object = try CBShortNetwork(json: json)
                    networks.append(object)
                } catch let error {
                    print(error)
                }
            }
        }
        self.networks = networks
    }
}

extension CBNetworksList {

    func toParams() -> APIParams {
        var params = [String: Any]()
        var networks = [[String: Any]]()
        for object in self.networks {
            if let param = object.toParams() {
                networks.append(param)
            }
        }
        params["networks"] = networks
        return params
    }

}

