//
// CBShortNetwork.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBShortNetwork {

    public var id: String?
    public var name: String?
    public var href: String?
    public var company: [String]?
    public var location: CBShortNetworkLocation?

    public init(id: String?, name: String?, href: String?, company: [String]?, location: CBShortNetworkLocation?) {
        if let id = id {
            self.id = id
        }
        if let name = name {
            self.name = name
        }
        if let href = href {
            self.href = href
        }
        if let company = company {
            self.company = company
        }
        if let location = location {
            self.location = location
        }
    }

    init(json: JSON) throws {
        let id = json["id"].string
        let name = json["name"].string
        let href = json["href"].string
        var company = [String]()
        if let companyJSON = json["company"].array {
            for json in companyJSON {
                if let object = json.string {
                    company.append(object)
                }
            }
        }
        let location = try? CBShortNetworkLocation(json: json["location"])
        self.id = id
        self.name = name
        self.href = href
        self.company = company
        self.location = location
    }
}

extension CBShortNetwork {

    func toParams() -> APIParams {
        var params = [String: Any]()
        if let id = id { params["id"] = id }
        if let name = name { params["name"] = name }
        if let href = href { params["href"] = href }
        params["company"] = self.company
        if let location = location { params["location"] = location }
        return params
    }

}

