//
// CBShortNetworkLocation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBShortNetworkLocation {

    public var city: String?
    public var country: String?
    public var latitude: Double?
    public var longitude: Double?

    public init(city: String?, country: String?, latitude: Double?, longitude: Double?) {
        if let city = city {
            self.city = city
        }
        if let country = country {
            self.country = country
        }
        if let latitude = latitude {
            self.latitude = latitude
        }
        if let longitude = longitude {
            self.longitude = longitude
        }
    }

    init(json: JSON) throws {
        let city = json["city"].string
        let country = json["country"].string
        let latitude = json["latitude"].double
        let longitude = json["longitude"].double
        self.city = city
        self.country = country
        self.latitude = latitude
        self.longitude = longitude
    }
}

extension CBShortNetworkLocation {

    func toParams() -> APIParams {
        var params = [String: Any]()
        if let city = city { params["city"] = city }
        if let country = country { params["country"] = country }
        if let latitude = latitude { params["latitude"] = latitude }
        if let longitude = longitude { params["longitude"] = longitude }
        return params
    }

}

