//
// CBStation.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBStation {

    public var id: String?
    public var name: String?
    public var latitude: Double?
    public var longitude: Double?
    public var freeBikes: Int?
    public var emptySlots: Int?
    public var timestamp: String?
    public var extra: CBStationExtra?

    public init(id: String?, name: String?, latitude: Double?, longitude: Double?, freeBikes: Int?, emptySlots: Int?, timestamp: String?, extra: CBStationExtra?) {
        if let id = id {
            self.id = id
        }
        if let name = name {
            self.name = name
        }
        if let latitude = latitude {
            self.latitude = latitude
        }
        if let longitude = longitude {
            self.longitude = longitude
        }
        if let freeBikes = freeBikes {
            self.freeBikes = freeBikes
        }
        if let emptySlots = emptySlots {
            self.emptySlots = emptySlots
        }
        if let timestamp = timestamp {
            self.timestamp = timestamp
        }
        if let extra = extra {
            self.extra = extra
        }
    }

    init(json: JSON) throws {
        let id = json["id"].string
        let name = json["name"].string
        let latitude = json["latitude"].double
        let longitude = json["longitude"].double
        let freeBikes = json["free_bikes"].int
        let emptySlots = json["empty_slots"].int
        let timestamp = json["timestamp"].string
        let extra = try? CBStationExtra(json: json["extra"])
        self.id = id
        self.name = name
        self.latitude = latitude
        self.longitude = longitude
        self.freeBikes = freeBikes
        self.emptySlots = emptySlots
        self.timestamp = timestamp
        self.extra = extra
    }
}

extension CBStation {

    func toParams() -> APIParams {
        var params = [String: Any]()
        if let id = id { params["id"] = id }
        if let name = name { params["name"] = name }
        if let latitude = latitude { params["latitude"] = latitude }
        if let longitude = longitude { params["longitude"] = longitude }
        if let freeBikes = freeBikes { params["free_bikes"] = freeBikes }
        if let emptySlots = emptySlots { params["empty_slots"] = emptySlots }
        if let timestamp = timestamp { params["timestamp"] = timestamp }
        if let extra = extra { params["extra"] = extra }
        return params
    }

}

