//
// CBStationExtra.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import SwiftyJSON


open class CBStationExtra {

    public enum CBStatus: String { 
        case open = "OPEN"
        case closed = "CLOSED"
    }
    public var address: String?
    public var banking: Bool?
    public var bonus: Bool?
    public var slots: Int?
    public var status: CBStatus?
    public var lastUpdate: Double?
    public var uid: Int?

    public init(address: String?, banking: Bool?, bonus: Bool?, slots: Int?, status: CBStatus?, lastUpdate: Double?, uid: Int?) {
        if let address = address {
            self.address = address
        }
        if let banking = banking {
            self.banking = banking
        }
        if let bonus = bonus {
            self.bonus = bonus
        }
        if let slots = slots {
            self.slots = slots
        }
        if let status = status {
            self.status = status
        }
        if let lastUpdate = lastUpdate {
            self.lastUpdate = lastUpdate
        }
        if let uid = uid {
            self.uid = uid
        }
    }

    init(json: JSON) throws {
        let address = json["address"].string
        let banking = json["banking"].bool
        let bonus = json["bonus"].bool
        let slots = json["slots"].int
        let status = CBStatus(rawValue: json["status"].stringValue)
        let lastUpdate = json["last_update"].double
        let uid = json["uid"].int
        self.address = address
        self.banking = banking
        self.bonus = bonus
        self.slots = slots
        self.status = status
        self.lastUpdate = lastUpdate
        self.uid = uid
    }
}

extension CBStationExtra {

    func toParams() -> APIParams {
        var params = [String: Any]()
        if let address = address { params["address"] = address }
        if let banking = banking { params["banking"] = banking }
        if let bonus = bonus { params["bonus"] = bonus }
        if let slots = slots { params["slots"] = slots }
        if let status = status { params["status"] = status.rawValue }
        if let lastUpdate = lastUpdate { params["last_update"] = lastUpdate }
        if let uid = uid { params["uid"] = uid }
        return params
    }

}

